### ISSUE TITLE
Self - Data

### ISSUE THREAD

**Issue by TommyHy9556** [zhijieW-94/SAGNet#2]
Hi, sorry for interrupting again.
After running your code, I find your result is extremely outstanding compared with those existing algorithms.  I am a researcher at University of Pennsylvania, and my direction is the geometry study in architecture design. By following the format of the data you provided, I tried to create my own data.  I put my own data which are architectural components in the 'chair' folder because it seems like you already set some voxel_loss_weights to different classes which honestly I am not sure what it is right now. But anyway, some problems show up.

vert_lr: 0.600000, edge_lr: 0.100000, graph_gen_lr: 0.100000, kl_loss_ratio: 1.000000
train neural network---------------------------------------------------
Traceback (most recent call last):
  File "train_net.py", line 164, in <module>
    train_net(sess=sess, config_dict=c_dict)
  File "train_net.py", line 133, in train_net
    _, summaries = train_net.train(sess, f_dict, cur_iter, is_summary=True)
  File "/home/tommy/Desktop/SAGNet-master/SAG_network.py", line 1064, in train
    outputs = sess.run(output_feed, input_feed)
  File "/home/tommy/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/tommy/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/tommy/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/tommy/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Nan in summary histogram for: part_voxel_decoder/part_voxel_decoder_bn/BatchNorm/beta_gradient
	 [[Node: part_voxel_decoder/part_voxel_decoder_bn/BatchNorm/beta_gradient = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](part_voxel_decoder/part_voxel_decoder_bn/BatchNorm/beta_gradient/tag, Mean_118/_1229)]]

Caused by op u'part_voxel_decoder/part_voxel_decoder_bn/BatchNorm/beta_gradient', defined at:
  File "train_net.py", line 164, in <module>
    train_net(sess=sess, config_dict=c_dict)
  File "train_net.py", line 68, in train_net
    train_net.setup()
  File "/home/tommy/Desktop/SAGNet-master/SAG_network.py", line 71, in setup
    self.setup_for_training()
  File "/home/tommy/Desktop/SAGNet-master/SAG_network.py", line 198, in setup_for_training
    tf.contrib.training.add_gradients_summaries(vert_grads_and_vars)
  File "/home/tommy/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/contrib/training/python/training/training.py", line 288, in add_gradients_summaries
    summary.histogram(var.op.name + '_gradient', grad_values))
  File "/home/tommy/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/summary/summary.py", line 203, in histogram
    tag=tag, values=values, name=scope)
  File "/home/tommy/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/ops/gen_logging_ops.py", line 283, in histogram_summary
    "HistogramSummary", tag=tag, values=values, name=name)
  File "/home/tommy/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/tommy/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/home/tommy/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Nan in summary histogram for: part_voxel_decoder/part_voxel_decoder_bn/BatchNorm/beta_gradient
	 [[Node: part_voxel_decoder/part_voxel_decoder_bn/BatchNorm/beta_gradient = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](part_voxel_decoder/part_voxel_decoder_bn/BatchNorm/beta_gradient/tag, Mean_118/_1229)]]

Below is the link of my own data.  I guess there are some parts I went wrong with. 
https://drive.google.com/open?id=1csWbXiKo0NIwC2uZdpimiTWyHD8SxGgP

I will really appreciate that if you can take a look at it or give me some hints about how to prepare my own data! If you want, I can share all the data I made or the following research results with you. Anyway, thank you very much!

**Comment by zhijieW94** [comment]
Hi, I will take a look this afternoon and then let us discuss more.

**Comment by zhijieW94** [comment]
Hi,

when did the NAN appear in the summary histogram? At the beginning (Iteration 0 or 1)? Or when training for a while (e.g., iteration 1000 or 5000)?

I'm sorry to say that, under current circumstances, I can't directly visualize your data and locate the true problems you have (I have left the lab for months).

But I would like to share some opinions with you:
1. please make sure your 3D shapes are zero-centered and well-oriented (our shapes in one category, like chair, have the same orientation). This step can relieve the training burden of our model. You can use some tools (e.g. meshlab) to confirm this point visually.
2. please let your 3D shapes share the same part order with our data. The consistent order is important to the training.
3. pay attention to the preprocessing codes in data_helper.py. As you can see, we have preprocessed the bounding box and voxel map data before feeding them into the model. I don't know if this step matter, as I can't directly analyze your shapes.

Do you want our original mesh data? It was collected from ShapeNet and manually segmented by ourselves. Maybe it can help you analyze your data problems.

I think, maybe it is better to share all you data. And then I can ask other collaborators for help.

**Comment by TommyHy9556** [comment]
Thank for your fast reply!

The error shows up at iteration 0.  It will be great if you can share the original meshes which I can study first. Other files in preparing the data will also be helpful. I guess my problems are about the orientation which I have not considered in my data.

I did all the models in Rhinoceros and wrote some simple scripts in the plugin called grasshopper which I guess maybe a little bit uncomfortable for you guys to read.  And then I get the mat data like what I just post.

For your convenience, maybe I can start with your meshes and do some adjustments to my data first. Then whether I succeed or fail, I will share the experience of preparing data with you and anyone who is interesting in this network.

Thank you!

**Comment by zhijieW94** [comment]
Thanks for your kindness and understanding. :-)

I will give you the original meshes and codes to voxelize them first. Maybe the codes are a bit messy.:-) And tomorrow I will share some other data preparation codes with you if I find them. 

The link of the meshes: https://drive.google.com/open?id=17mnqYycNSUyV6ScOABZBkaF55mfCBOCi.
The link of the voxelizer: https://drive.google.com/open?id=0ByrK3yYLgwU1VGNtUWhIa0NKTThDUnc0Z0N4SDJpUXlBWWNJ.

For the voxelizer, you can start from voxelizerMain.cpp.

**Comment by zhijieW94** [comment]
Hi,

I forgot to say that, I didn't find any other data preparation codes to extract the bounding boxes in the past two days.  But I think they are simple and maybe will not influence your understanding on how we prepare our training data.

**Comment by TommyHy9556** [comment]
Thank you for your kindness! 
I guess there are some tricky parts of the data both you and I ignore. lol. Because even when I use your data but in a very small number, say, 40 chair models, the same issue comes out. But if I add my data to your raw chair models folder, the network can really work. So basically my strategy is that in one training process, I use most of my own data and add some data you give, the training can start, and the result is not bad also. 

Anyway, I just close this issue. If there is more progress, I will post it!

**Comment by zhijieW94** [comment]
Yes. In fact, from the very beginning, we have trained our model with the full collected dataset. And we do not consider too much about it.

Look forward to your new progress!
