### ISSUE TITLE
some questions about training data

### ISSUE THREAD

**Issue by CRISZJ** [zhijieW-94/SAGNet#3]
Hi, wonderful job. it seems that your work's dataset's version is .mat, and I want to konw how to convert the dataset's file like .off or .obj to the verison of .mat. thanks

**Comment by CRISZJ** [comment]
> Hi, wonderful job. I want to konw how to convert the dataset's file like .off or .obj to the verison of .mat

**Comment by zhijieW94** [comment]
Hi, thanks for your interests in our work. In fact, I would like to say that some other people have asked almost the same question.

Our dataset consists of .mat files (for voxel maps) and .txt files (for bounding boxes). I can share our voxelization codes and our original meshes with you to let you better adapt your own data.

The link of the meshes: https://drive.google.com/open?id=17mnqYycNSUyV6ScOABZBkaF55mfCBOCi.
The link of the voxelizer: https://drive.google.com/open?id=0ByrK3yYLgwU1VGNtUWhIa0NKTThDUnc0Z0N4SDJpUXlBWWNJ.

**Comment by CRISZJ** [comment]
> Hi, thanks for your interests in our work. In fact, I would like to say that some other people have asked almost the same question.
> 
> Our dataset consists of .mat files (for voxel maps) and .txt files (for bounding boxes). I can share our voxelization codes and our original meshes with you to let you better adapt your own data.
> 
> The link of the meshes: https://drive.google.com/open?id=17mnqYycNSUyV6ScOABZBkaF55mfCBOCi.
> The link of the voxelizer: https://drive.google.com/open?id=0ByrK3yYLgwU1VGNtUWhIa0NKTThDUnc0Z0N4SDJpUXlBWWNJ.

thanks
