### ISSUE TITLE
some questions about visualize

### ISSUE THREAD

**Issue by CRISZJ** [zhijieW-94/SAGNet#4]
Hi, When i use the pyqt tool to visualize(python application.py), i meet this problem:
 if obj_names[0].find('iter_') != -1:
IndexError: list index out of range
Aborted (core dumped)

**Comment by zhijieW94** [comment]
Hi,

to visualize the provided shapes, please set up the environment correctly first. And then open the right directories. It seems that you open an empty directory?

As far as I know, others who use the offered environment can successfully visualize the 3D shapes. So please try again. :-)

**Comment by CRISZJ** [comment]
> Hi,
> 
> to visualize the provided shapes, please set up the environment correctly first. And then open the right directories. It seems that you open an empty directory?
> 
> As far as I know, others who use the offered environment can successfully visualize the 3D shapes. So please try again. :-)

thanks for your reply,
 
this is becasue i use python2 and pyhton3 together. because i can't build pyqt5 upon the pyhton2's enviroments. could you please tell me how to ues the enviroment of yours(ananconda2)? I use it to replace the file in my anaconda. it seems it is not right. 

 thanks again

**Comment by CRISZJ** [comment]
I meet this problem when I visualize the model. as follows:
Falling back to using screens root_visual.
success
32 32 32
-0.007469 -0.204488 0.006789
part index: 0 center: (0.0, 0.0, 0.0)
part index: 0 position: (0.0, 0.0, 0.0)
part index: 0 xRange: (1.0, -1.0)
part index: 0 length: 3.4641016151377544
part index: 0 translate_vector: [-0.007469, -0.204488, 0.006789]
part index: 0 dims_vector: [0.03611, 0.318037, 0.236558]
32 32 32
-0.024679 0.481333 0.008463
part index: 1 center: (0.0, 0.0, 0.0)
part index: 1 position: (0.0, 0.0, 0.0)
part index: 1 xRange: (1.0, -1.0)
part index: 1 length: 3.4641016151377544
part index: 1 translate_vector: [-0.024679, 0.481333, 0.008463]
part index: 1 dims_vector: [0.060845, 0.172604, 0.11272]
32 32 32
-0.006909 0.14532 0.00765
part index: 2 center: (0.0, 0.0, 0.0)
part index: 2 position: (0.0, 0.0, 0.0)
part index: 2 xRange: (1.0, -1.0)
part index: 2 length: 3.4641016151377544
part index: 2 translate_vector: [-0.006909, 0.14532, 0.00765]
part index: 2 dims_vector: [0.031883, 0.557201, 0.05976]
(0.0, 0.0, 0.0)
(0.0, 0.0, 0.0)
(0.0, 0.0, 0.0)
No XVisualInfo for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(SingleBuffer), swapInterval 1, colorSpace QSurfaceFormat::ColorSpace(DefaultColorSpace), profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
Falling back to using screens root_visual.
