### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by CRISZJ** [zhijieW-94/SAGNet#5]
hi , thanks for your dataset, but the dataset of guitar maybe is not right . when i visualize guitar, it seems tha it noly has one structure of the guitar, although it has three different mat. so ,could you please to ensure it is right? thanks again.

**Comment by zhijieW94** [comment]
Well, the uploaded datasets have been checked before and they all are right. But they will be double checked. If they are wrong, I will send you the right one later.

**Comment by CRISZJ** [comment]
> Well, the uploaded datasets have been checked before and they all are right. But they will be double checked. If they are wrong, I will send you the right one later.

thanks for your reply. most of them are correct, except for guitar, maybe it is my error, so i want to confirm with you

**Comment by CRISZJ** [comment]
> Well, the uploaded datasets have been checked before and they all are right. But they will be double checked. If they are wrong, I will send you the right one later.

sorry,it's my error, thanks again. : )

**Comment by CRISZJ** [comment]
sorry for bather you again, i saw your paper compare with G2LGAN, do you have the dataset of G2LGAN? like lamp and so on. it is not involved in the page of G2LGAN. thanks

**Comment by zhijieW94** [comment]
No, I do not have the dataset of G2LGAN. As you can see, we only tested the methods on our own dataset.

**Comment by zhijieW94** [comment]
No, I do not have the dataset of G2LGAN. As you can see, we only tested the methods on our own dataset.
