### ISSUE TITLE
testing use MMD and COV

### ISSUE THREAD

**Issue by CRISZJ** [zhijieW-94/SAGNet#6]
thanks for your code and data. 
i have a quesiton in your paper. when you  test your data by MMD and COV, how to fix the number of point cloud for each part? the MMD and COV methods fix the number of point cloud to 2048 for each model. 
 looking forward to your reply, thanks a lot  : ）

**Comment by zhijieW94** [comment]
Sorry for my late response. To compute the MMD and COV, we randomly sample a fixed number of points from the generated shapes.

**Comment by CRISZJ** [comment]
thanks for your reply. could you please tell me the number of points?

**Comment by zhijieW94** [comment]
For the voxel map of each part, we sample 512 points for evaluation.

**Comment by CRISZJ** [comment]
> For the voxel map of each part, we sample 512 points for evaluation.

thanks , and I also have a question with dataset. Is the bounding-box in the datset parallel to the x, y, and z coordinate axes when segmenting the object? In other words, can we get the coordinates of the eight vertices of the bounding-box through the coordinates of the center point and the length, width and height of the bounding-box?
thanks again. looking forward to your reply :-)

**Comment by zhijieW94** [comment]
Yes, they are axis-aligned bounding boxes so we can localize the bound boxes via the positions of center points and the corresponding dimension sizes.
